version: "3.8"

services:
  anilibria-proxy:
    image: gederfix/anilibria-proxy:latest
    container_name: anilibria-proxy
    restart: unless-stopped
    ports:
      - "5003:5001"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true